// js/state.js — État mutable partagé et références DOM

import { DEFAULT_SCHOOL_LEVEL, INTENT, MODE, OP, TIME_LIMIT } from './config.js';

const elements = {
  score:               document.getElementById('current-score'),
  bar:                 document.getElementById('timer-bar'),
  counter:             document.getElementById('q-counter'),
  question:            document.getElementById('question'),
  buddy:               document.getElementById('buddy'),
  buddyIcon:           document.getElementById('buddy-icon'),
  buddyName:           document.getElementById('buddy-name'),
  feedback:            document.getElementById('feedback'),
  input:               document.getElementById('answer-input'),
  startBtn:            document.getElementById('start-btn'),
  stopBtn:             document.getElementById('stop-btn'),
  endScreen:           document.getElementById('end-screen'),
  endScoreValue:       document.getElementById('end-score-value'),
  endLabel:            document.getElementById('end-label'),
  playAgainBtn:        document.getElementById('play-again-btn'),
  changePlayerBtn:     document.getElementById('change-player-btn'),
  playerHeaderRow:     document.getElementById('player-header-row'),
  profileModalOverlay: document.getElementById('profile-modal-overlay'),
  profilePickerView:   document.getElementById('profile-picker-view'),
  profileLanguageSwitch: document.getElementById('profile-language-switch'),
  profileLanguageLabel: document.getElementById('profile-language-label'),
  profileLanguageOptions: document.getElementById('profile-language-options'),
  profileCreateView:   document.getElementById('profile-create-view'),
  profileList:         document.getElementById('profile-list'),
  profileNewBtn:       document.getElementById('profile-new-btn'),
  profileGuestBtn:     document.getElementById('profile-guest-btn'),
  profileNameInput:    document.getElementById('profile-name-input'),
  avatarGrid:          document.getElementById('avatar-grid'),
  profileCreateError:  document.getElementById('profile-create-error'),
  profileCreateConfirmBtn: document.getElementById('profile-create-confirm-btn'),
  profileCreateCancelBtn:  document.getElementById('profile-create-cancel-btn'),
  profileEditView:         document.getElementById('profile-edit-view'),
  profileEditNameInput:    document.getElementById('profile-edit-name-input'),
  avatarGridEdit:          document.getElementById('avatar-grid-edit'),
  profileEditError:        document.getElementById('profile-edit-error'),
  profileEditConfirmBtn:   document.getElementById('profile-edit-confirm-btn'),
  profileEditCancelBtn:    document.getElementById('profile-edit-cancel-btn'),
  profileDeleteBtn:        document.getElementById('profile-delete-btn'),
  profileDeleteConfirm:    document.getElementById('profile-delete-confirm'),
  profileDeleteConfirmBtn: document.getElementById('profile-delete-confirm-btn'),
  profileDeleteCancelBtn:  document.getElementById('profile-delete-cancel-btn'),
  playerDisplayName:   document.getElementById('player-display-name'),
  endPlayerNameSection:document.getElementById('end-player-name-section'),
  endPlayerNameValue:  document.getElementById('end-player-name-value'),
  classementLevelSelector: document.getElementById('classement-level-selector'),
  leaderboardSection:      document.getElementById('leaderboard-section'),
  leaderboardSectionTitle: document.getElementById('leaderboard-section-title'),
  leaderboardBody:         document.getElementById('leaderboard-body'),
  leaderboardPanel:        document.getElementById('leaderboard-panel'),
  leaderboardPanelBody:    document.getElementById('leaderboard-panel-body'),
  survieLeaderboardPanel:     document.getElementById('survie-leaderboard-panel'),
  survieLeaderboardPanelBody: document.getElementById('survie-leaderboard-panel-body'),
  leaderboardEmptyHint:      document.getElementById('leaderboard-empty-hint'),
  numpad:       document.getElementById('numpad'),
  posedActions: document.getElementById('posed-actions'),
  answerDisplay:document.getElementById('answer-display'),
  confettiLayer:document.getElementById('confetti-layer'),
  gamePlayArea: document.getElementById('game-play-area'),
  timerTrack:   document.getElementById('timer-track'),
  scoreCard:    document.getElementById('score-card'),
  streakCard:    document.getElementById('streak-card'),
  currentStreak: document.getElementById('current-streak'),
  tabBar:           document.getElementById('tab-bar'),
  tabJouer:         document.getElementById('tab-jouer'),
  tabClassement:    document.getElementById('tab-classement'),
  tabProgression:   document.getElementById('tab-progression'),
  panelJouer:       document.getElementById('panel-jouer'),
  panelClassement:  document.getElementById('panel-classement'),
  panelProgression: document.getElementById('panel-progression'),
  progressionTerrains: document.getElementById('progression-terrains'),
  progressionBody:  document.getElementById('progression-body'),
  modeTriggerRow:     document.getElementById('mode-trigger-row'),
  modeTrigger:        document.getElementById('mode-trigger'),
  modeSummaryTags:    document.getElementById('mode-summary-tags'),
  modeSummaryType:    document.getElementById('mode-summary-type'),
  modeSummaryIntent:  document.getElementById('mode-summary-intent'),
  modeSummaryOp:      document.getElementById('mode-summary-op'),
  modeSummaryLevel:   document.getElementById('mode-summary-level'),
  modeMenu:           document.getElementById('mode-menu'),
  modeMenuCloseBtn:   document.getElementById('mode-menu-close-btn'),
  modeMenuSectionType: document.getElementById('mode-menu-section-type'),
  modeMenuSectionOp:   document.getElementById('mode-menu-section-op'),
  modeMenuSectionIntent: document.getElementById('mode-menu-section-intent'),
  modeMenuSectionLevel: document.getElementById('mode-menu-section-level'),
  modeOpRow:          document.getElementById('mode-op-row'),
  modeIntentRow:      document.getElementById('mode-intent-row'),
  modeDrawerBackdrop: document.getElementById('mode-drawer-backdrop'),
  schoolLevelRow:       document.getElementById('school-level-row'),
  activeSchoolLevel:    document.getElementById('active-school-level'),
  settingsBtn:             document.getElementById('settings-btn'),
  languageSwitch:          document.getElementById('language-switch'),
  languageBtn:             document.getElementById('language-btn'),
  languageMenu:            document.getElementById('language-menu'),
  settingsModalOverlay:    document.getElementById('settings-modal-overlay'),
  settingsCloseBtn:        document.getElementById('settings-close-btn'),
  settingsPersonalLabel:   document.getElementById('settings-personal-label'),
  themeOptions:            document.getElementById('theme-options'),
  layoutOptions:           document.getElementById('layout-options'),
  leaderboardResetCodeInput: document.getElementById('leaderboard-reset-code-input'),
  leaderboardResetBtn:       document.getElementById('leaderboard-reset-btn'),
  leaderboardResetMessage:   document.getElementById('leaderboard-reset-message'),
};

export const state = {
  currentMode:          MODE.DEFI_MIX,
  currentQ:             null,
  roundQuestionFingerprints: new Set(),
  score:                0,
  questionNumber:       0,
  startTime:            0,
  rafId:                null,
  locked:               false,
  profiles:             [],
  activeProfileId:      null,
  activeProfile:        null,
  isGuestSession:       false,
  sessionPlayerSelected:false,
  gameInProgress:       false,
  inputBuffer:          '',
  streak:               0,
  pendingStart:         false,
  sessionActive:        false,
  gameType:             'mental',
  progressionType:      'mental',
  progressionOp:        OP.MIX,
  progressionIntent:    INTENT.DEFI,
  progressionLevel:     null,
  currentSchoolLevel:   DEFAULT_SCHOOL_LEVEL,
  classementLevel:      DEFAULT_SCHOOL_LEVEL,
  currentTimeLimit:     TIME_LIMIT,
  theme:                'light',
  keyboardLayout:       'pc',

  elements,
};
